name: karabiner_session_monitor

targets:
  karabiner_session_monitor:
    settings:
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      HEADER_SEARCH_PATHS:
        - include
        - ../../share
      OTHER_SWIFT_FLAGS: '-warnings-as-errors'
      SWIFT_OBJC_BRIDGING_HEADER: swift/Bridging-Header.h
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../../vendor/Karabiner-DriverKit-VirtualHIDDevice/include
        - ../../../vendor/vendor/include
      DEAD_CODE_STRIPPING: 'YES'
    type: tool
    platform: macOS
    deploymentTarget: 13.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
          - '-std=c++20'
      - path: ../../../vendor/vendor/src/pqrs/osx/process_info
      - path: ../../../vendor/vendor/src/pqrs/osx/workspace
    dependencies:
      - framework: CoreGraphics.framework
      - framework: CoreServices.framework
