name: Karabiner-Elements CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Xcode 16.3
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: brew install
        run: brew install xcodegen
      - name: package
        run: make package
      - name: appendix
        run: ruby scripts/reduce-logs.rb 'make -C appendix'
      - name: tests
        run: ruby scripts/reduce-logs.rb 'make -C tests'
